export interface Currency {
  code: string
  name: string
  symbol: string
}

/** Currency codes shown at the top of the picker, ahead of the A-Z list. */
export const POPULAR_CURRENCY_CODES = ['USD', 'EUR', 'GBP', 'JPY', 'CAD', 'AUD', 'INR', 'CNY', 'CHF', 'NZD']

const BY_CODE: Record<string, Currency> = {}

export function getCurrency(code: string): Currency | undefined {
  return BY_CODE[code]
}

export function getCurrencySymbol(code: string): string {
  return BY_CODE[code]?.symbol ?? code
}

/** Best-effort country-to-currency lookup for the visitor's browser locale, covering major economies. */
const REGION_TO_CURRENCY: Record<string, string> = {
  US: 'USD', GB: 'GBP', IE: 'EUR', CA: 'CAD', AU: 'AUD', NZ: 'NZD',
  DE: 'EUR', FR: 'EUR', ES: 'EUR', IT: 'EUR', NL: 'EUR', PT: 'EUR',
  BE: 'EUR', AT: 'EUR', FI: 'EUR', GR: 'EUR',
  JP: 'JPY', CN: 'CNY', IN: 'INR', KR: 'KRW', SG: 'SGD', HK: 'HKD',
  CH: 'CHF', SE: 'SEK', NO: 'NOK', DK: 'DKK', PL: 'PLN', CZ: 'CZK',
  BR: 'BRL', MX: 'MXN', ZA: 'ZAR', NG: 'NGN', KE: 'KES', EG: 'EGP',
  AE: 'AED', SA: 'SAR', IL: 'ILS', TR: 'TRY', RU: 'RUB', UA: 'UAH',
  PH: 'PHP', ID: 'IDR', MY: 'MYR', TH: 'THB', VN: 'VND', PK: 'PKR',
  BD: 'BDT', AR: 'ARS', CL: 'CLP', CO: 'COP', PE: 'PEN',
}

export function guessCurrencyFromLocale(): string {
  if (typeof navigator === 'undefined') return 'USD'
  for (const locale of navigator.languages ?? [navigator.language]) {
    try {
      const region = new Intl.Locale(locale).maximize().region
      if (region && REGION_TO_CURRENCY[region]) return REGION_TO_CURRENCY[region]
    } catch {
      // ignore unparseable locale
    }
  }
  return 'USD'
}

export const CURRENCIES: Currency[] = [
  { code: 'AFN', name: 'Afghan Afghani', symbol: '؋' },
  { code: 'ALL', name: 'Albanian Lek', symbol: 'ALL' },
  { code: 'DZD', name: 'Algerian Dinar', symbol: 'DZD' },
  { code: 'AOA', name: 'Angolan Kwanza', symbol: 'Kz' },
  { code: 'ARS', name: 'Argentine Peso', symbol: '$' },
  { code: 'AMD', name: 'Armenian Dram', symbol: '֏' },
  { code: 'AWG', name: 'Aruban Florin', symbol: 'AWG' },
  { code: 'AUD', name: 'Australian Dollar', symbol: '$' },
  { code: 'AZN', name: 'Azerbaijani Manat', symbol: '₼' },
  { code: 'BSD', name: 'Bahamian Dollar', symbol: '$' },
  { code: 'BHD', name: 'Bahraini Dinar', symbol: 'BHD' },
  { code: 'BDT', name: 'Bangladeshi Taka', symbol: '৳' },
  { code: 'BBD', name: 'Barbadian Dollar', symbol: '$' },
  { code: 'BYN', name: 'Belarusian Ruble', symbol: 'BYN' },
  { code: 'BZD', name: 'Belize Dollar', symbol: '$' },
  { code: 'BMD', name: 'Bermudan Dollar', symbol: '$' },
  { code: 'BTN', name: 'Bhutanese Ngultrum', symbol: 'BTN' },
  { code: 'BOB', name: 'Bolivian Boliviano', symbol: 'Bs' },
  { code: 'BAM', name: 'Bosnia-Herzegovina Convertible Mark', symbol: 'KM' },
  { code: 'BWP', name: 'Botswanan Pula', symbol: 'P' },
  { code: 'BRL', name: 'Brazilian Real', symbol: 'R$' },
  { code: 'GBP', name: 'British Pound', symbol: '£' },
  { code: 'BND', name: 'Brunei Dollar', symbol: '$' },
  { code: 'BGN', name: 'Bulgarian Lev', symbol: 'BGN' },
  { code: 'BIF', name: 'Burundian Franc', symbol: 'BIF' },
  { code: 'KHR', name: 'Cambodian Riel', symbol: '៛' },
  { code: 'CAD', name: 'Canadian Dollar', symbol: '$' },
  { code: 'CVE', name: 'Cape Verdean Escudo', symbol: 'CVE' },
  { code: 'XCG', name: 'Caribbean guilder', symbol: 'Cg.' },
  { code: 'KYD', name: 'Cayman Islands Dollar', symbol: '$' },
  { code: 'XAF', name: 'Central African CFA Franc', symbol: 'FCFA' },
  { code: 'XPF', name: 'CFP Franc', symbol: 'CFPF' },
  { code: 'CLP', name: 'Chilean Peso', symbol: '$' },
  { code: 'CNY', name: 'Chinese Yuan', symbol: '¥' },
  { code: 'COP', name: 'Colombian Peso', symbol: '$' },
  { code: 'KMF', name: 'Comorian Franc', symbol: 'CF' },
  { code: 'CDF', name: 'Congolese Franc', symbol: 'CDF' },
  { code: 'CRC', name: 'Costa Rican Colón', symbol: '₡' },
  { code: 'HRK', name: 'Croatian Kuna', symbol: 'kn' },
  { code: 'CUC', name: 'Cuban Convertible Peso', symbol: '$' },
  { code: 'CUP', name: 'Cuban Peso', symbol: '$' },
  { code: 'CZK', name: 'Czech Koruna', symbol: 'Kč' },
  { code: 'DKK', name: 'Danish Krone', symbol: 'kr' },
  { code: 'DJF', name: 'Djiboutian Franc', symbol: 'DJF' },
  { code: 'DOP', name: 'Dominican Peso', symbol: '$' },
  { code: 'XCD', name: 'East Caribbean Dollar', symbol: '$' },
  { code: 'EGP', name: 'Egyptian Pound', symbol: 'E£' },
  { code: 'ERN', name: 'Eritrean Nakfa', symbol: 'ERN' },
  { code: 'ETB', name: 'Ethiopian Birr', symbol: 'ETB' },
  { code: 'EUR', name: 'Euro', symbol: '€' },
  { code: 'FKP', name: 'Falkland Islands Pound', symbol: '£' },
  { code: 'FJD', name: 'Fijian Dollar', symbol: '$' },
  { code: 'GMD', name: 'Gambian Dalasi', symbol: 'GMD' },
  { code: 'GEL', name: 'Georgian Lari', symbol: '₾' },
  { code: 'GHS', name: 'Ghanaian Cedi', symbol: 'GH₵' },
  { code: 'GIP', name: 'Gibraltar Pound', symbol: '£' },
  { code: 'GTQ', name: 'Guatemalan Quetzal', symbol: 'Q' },
  { code: 'GNF', name: 'Guinean Franc', symbol: 'FG' },
  { code: 'GYD', name: 'Guyanaese Dollar', symbol: '$' },
  { code: 'HTG', name: 'Haitian Gourde', symbol: 'HTG' },
  { code: 'HNL', name: 'Honduran Lempira', symbol: 'L' },
  { code: 'HKD', name: 'Hong Kong Dollar', symbol: '$' },
  { code: 'HUF', name: 'Hungarian Forint', symbol: 'Ft' },
  { code: 'ISK', name: 'Icelandic Króna', symbol: 'kr' },
  { code: 'INR', name: 'Indian Rupee', symbol: '₹' },
  { code: 'IDR', name: 'Indonesian Rupiah', symbol: 'Rp' },
  { code: 'IRR', name: 'Iranian Rial', symbol: 'IRR' },
  { code: 'IQD', name: 'Iraqi Dinar', symbol: 'IQD' },
  { code: 'ILS', name: 'Israeli New Shekel', symbol: '₪' },
  { code: 'JMD', name: 'Jamaican Dollar', symbol: '$' },
  { code: 'JPY', name: 'Japanese Yen', symbol: '¥' },
  { code: 'JOD', name: 'Jordanian Dinar', symbol: 'JOD' },
  { code: 'KZT', name: 'Kazakhstani Tenge', symbol: '₸' },
  { code: 'KES', name: 'Kenyan Shilling', symbol: 'KES' },
  { code: 'KWD', name: 'Kuwaiti Dinar', symbol: 'KWD' },
  { code: 'KGS', name: 'Kyrgyz Som', symbol: '⃀' },
  { code: 'LAK', name: 'Laotian Kip', symbol: '₭' },
  { code: 'LBP', name: 'Lebanese Pound', symbol: 'L£' },
  { code: 'LSL', name: 'Lesotho Loti', symbol: 'LSL' },
  { code: 'LRD', name: 'Liberian Dollar', symbol: '$' },
  { code: 'LYD', name: 'Libyan Dinar', symbol: 'LYD' },
  { code: 'MOP', name: 'Macanese Pataca', symbol: 'MOP' },
  { code: 'MKD', name: 'Macedonian Denar', symbol: 'MKD' },
  { code: 'MGA', name: 'Malagasy Ariary', symbol: 'Ar' },
  { code: 'MWK', name: 'Malawian Kwacha', symbol: 'MWK' },
  { code: 'MYR', name: 'Malaysian Ringgit', symbol: 'RM' },
  { code: 'MVR', name: 'Maldivian Rufiyaa', symbol: 'MVR' },
  { code: 'MRU', name: 'Mauritanian Ouguiya', symbol: 'MRU' },
  { code: 'MUR', name: 'Mauritian Rupee', symbol: 'Rs' },
  { code: 'MXN', name: 'Mexican Peso', symbol: '$' },
  { code: 'MDL', name: 'Moldovan Leu', symbol: 'MDL' },
  { code: 'MNT', name: 'Mongolian Tugrik', symbol: '₮' },
  { code: 'MAD', name: 'Moroccan Dirham', symbol: 'MAD' },
  { code: 'MZN', name: 'Mozambican Metical', symbol: 'MZN' },
  { code: 'MMK', name: 'Myanmar Kyat', symbol: 'K' },
  { code: 'NAD', name: 'Namibian Dollar', symbol: '$' },
  { code: 'NPR', name: 'Nepalese Rupee', symbol: 'Rs' },
  { code: 'ANG', name: 'Netherlands Antillean Guilder', symbol: 'ANG' },
  { code: 'TWD', name: 'New Taiwan Dollar', symbol: '$' },
  { code: 'NZD', name: 'New Zealand Dollar', symbol: '$' },
  { code: 'NIO', name: 'Nicaraguan Córdoba', symbol: 'C$' },
  { code: 'NGN', name: 'Nigerian Naira', symbol: '₦' },
  { code: 'KPW', name: 'North Korean Won', symbol: '₩' },
  { code: 'NOK', name: 'Norwegian Krone', symbol: 'kr' },
  { code: 'OMR', name: 'Omani Rial', symbol: 'OMR' },
  { code: 'PKR', name: 'Pakistani Rupee', symbol: 'Rs' },
  { code: 'PAB', name: 'Panamanian Balboa', symbol: 'PAB' },
  { code: 'PGK', name: 'Papua New Guinean Kina', symbol: 'PGK' },
  { code: 'PYG', name: 'Paraguayan Guarani', symbol: '₲' },
  { code: 'PEN', name: 'Peruvian Sol', symbol: 'PEN' },
  { code: 'PHP', name: 'Philippine Peso', symbol: '₱' },
  { code: 'PLN', name: 'Polish Zloty', symbol: 'zł' },
  { code: 'QAR', name: 'Qatari Riyal', symbol: 'QAR' },
  { code: 'RON', name: 'Romanian Leu', symbol: 'lei' },
  { code: 'RUB', name: 'Russian Ruble', symbol: '₽' },
  { code: 'RWF', name: 'Rwandan Franc', symbol: 'RF' },
  { code: 'SVC', name: 'Salvadoran Colón', symbol: 'SVC' },
  { code: 'WST', name: 'Samoan Tala', symbol: 'WST' },
  { code: 'STN', name: 'São Tomé & Príncipe Dobra', symbol: 'Db' },
  { code: 'SAR', name: 'Saudi Riyal', symbol: 'SAR' },
  { code: 'RSD', name: 'Serbian Dinar', symbol: 'RSD' },
  { code: 'SCR', name: 'Seychellois Rupee', symbol: 'SCR' },
  { code: 'SLE', name: 'Sierra Leonean Leone', symbol: 'SLE' },
  { code: 'SLL', name: 'Sierra Leonean Leone (1964—2022)', symbol: 'SLL' },
  { code: 'SGD', name: 'Singapore Dollar', symbol: '$' },
  { code: 'SBD', name: 'Solomon Islands Dollar', symbol: '$' },
  { code: 'SOS', name: 'Somali Shilling', symbol: 'SOS' },
  { code: 'ZAR', name: 'South African Rand', symbol: 'R' },
  { code: 'KRW', name: 'South Korean Won', symbol: '₩' },
  { code: 'SSP', name: 'South Sudanese Pound', symbol: '£' },
  { code: 'LKR', name: 'Sri Lankan Rupee', symbol: 'Rs' },
  { code: 'SHP', name: 'St. Helena Pound', symbol: '£' },
  { code: 'SDG', name: 'Sudanese Pound', symbol: 'SDG' },
  { code: 'SRD', name: 'Surinamese Dollar', symbol: '$' },
  { code: 'SZL', name: 'Swazi Lilangeni', symbol: 'SZL' },
  { code: 'SEK', name: 'Swedish Krona', symbol: 'kr' },
  { code: 'CHF', name: 'Swiss Franc', symbol: 'CHF' },
  { code: 'SYP', name: 'Syrian Pound', symbol: '£' },
  { code: 'TJS', name: 'Tajikistani Somoni', symbol: 'TJS' },
  { code: 'TZS', name: 'Tanzanian Shilling', symbol: 'TZS' },
  { code: 'THB', name: 'Thai Baht', symbol: '฿' },
  { code: 'TOP', name: 'Tongan Paʻanga', symbol: 'T$' },
  { code: 'TTD', name: 'Trinidad & Tobago Dollar', symbol: '$' },
  { code: 'TND', name: 'Tunisian Dinar', symbol: 'TND' },
  { code: 'TRY', name: 'Turkish Lira', symbol: '₺' },
  { code: 'TMT', name: 'Turkmenistani Manat', symbol: 'TMT' },
  { code: 'UGX', name: 'Ugandan Shilling', symbol: 'UGX' },
  { code: 'UAH', name: 'Ukrainian Hryvnia', symbol: '₴' },
  { code: 'AED', name: 'United Arab Emirates Dirham', symbol: 'AED' },
  { code: 'UYU', name: 'Uruguayan Peso', symbol: '$' },
  { code: 'USD', name: 'US Dollar', symbol: '$' },
  { code: 'UZS', name: 'Uzbekistani Som', symbol: 'UZS' },
  { code: 'VUV', name: 'Vanuatu Vatu', symbol: 'VUV' },
  { code: 'VES', name: 'Venezuelan Bolívar', symbol: 'VES' },
  { code: 'VND', name: 'Vietnamese Dong', symbol: '₫' },
  { code: 'XOF', name: 'West African CFA Franc', symbol: 'F CFA' },
  { code: 'YER', name: 'Yemeni Rial', symbol: 'YER' },
  { code: 'ZMW', name: 'Zambian Kwacha', symbol: 'ZK' },
  { code: 'ZWL', name: 'Zimbabwean Dollar (2009–2024)', symbol: 'ZWL' },
  { code: 'ZWG', name: 'Zimbabwean Gold', symbol: 'ZWG' },
]

for (const c of CURRENCIES) BY_CODE[c.code] = c
